### ISSUE TITLE
Network Indexer

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#236]
### Overview

Redesign and implement a more reliable backend for explorer that can be accessed by external users

### Requirements

- Indexed access to all
   - Transactions (by transaction hash, block hash, block timestamp, signer ID, receiver ID)
      - Actions (by transaction hash, action type)
      - Receipts (by receipt hash, signer ID, transaction hash)
  - Accounts (by account ID, creation timestamp [block timestamp], code hash #184 [indicates if it has a contract])
      - Mapping of keys to accounts
  - Blocks (by block hash, block timestamp)
      - Chunks (by chunk hash, block hash)
  - Access Keys (by public key, account ID) #162
  - State Changes (by account ID, type)
  - ~Nodes (validators)~ *(the current design of telemetry is out of the scope of this issue)*
- Reliable source of data

### How to Implement

UPD: We chose the internal API path: https://github.com/nearprotocol/nearcore/tree/master/chain/indexer

#### Using internal API (fast and feature-complete, but will require coordination with nearcore chain team):

- reuse near-network to sync the state with the network

#### Using public API (does not really provide any benefit):

- Fetch current block height
- Block by block (from genesis ["block 0"] to current height) poll and reconcile into one blob
  - RPC
  - State Changes API
- Push to indexer

**Comment by frol** [comment]
To collect all the information floating around, I will link previous discussions:

The possible implementations were discussed here: https://commonwealth.im/near/proposal/discussion/306-using-the-graph-for-indexing-blockchain-data

/cc @nearmax

**Comment by bowenwang1996** [comment]
@frol @kcole16 is nodejs the long term plan for the backend? Sort of feel like js is not designed for this type of service 🤔 but that could just be my ignorance.

**Comment by frol** [comment]
@bowenwang1996 We want to build it in Rust :smile: (even initially I strongly considered Rust for Explorer backend). TheGraph (I consider building on top of it and PR upstream) is implemented in Rust.

**Comment by bowenwang1996** [comment]
Rust ftw!

**Comment by vgrichina** [comment]
Dunno why you folks like using Rust for backend so much given nearcore RPC experience. Using Rust will discourage open source contributions, as there are far more JS developers than Rust developers. It's also looks like generally resulting far longer dev cycles (based on nearcore experience).

**Comment by vgrichina** [comment]
@frol this is highly desired for MainNet but not strictly a blocker. However if not dealt at nearcore/explorer layer – I'd likely have to implement it as separate service. We need it for wallet integration + useful in our wallet (e.g. to restore when you only have Ledger with public key on it).

**Comment by frol** [comment]
> Dunno why you folks like using Rust for backend so much given nearcore RPC experience.

nearcore RPC was a side-project to the chain and has been developed based on the immediate needs with tight time constraints to close those needs ASAP, also it exposes internal representation having quite a tight coupling with the internals which keep evolving and changed rapidly. Indexer is a much less complex component, but it still needs to be reliable. JS showed (and I knew this is going to beat us), that while it is easy to prototype, it is hard to maintain stability (working with numbers is a pain, it just silently rounds the data we send or get from the database).

> there are far more JS developers than Rust developers

While that is a true statement by itself. There are far fewer backend devs in JS than the total number, and it is much harder to review the code in JS than in Rust; also, TS does not solve all the problems either while reducing the number of possible contributors even more. Also, do we have much external contribution to our AppLayer projects? (on the Explorer, it is none)

>  I'd likely have to implement it as separate service.

Well, if that is the case, we should better implement it in Explorer backend since we almost have it.

**Comment by vgrichina** [comment]
> and has been developed based on the immediate needs with tight time constraints to close those needs 

Why do you think constraints would be different now? We are still a startup with no product market fit. It's too early to exit prototype mode for anything except blockchain base layer. Most of "Indexer" stuff is likely going to be completely deprecated if smth like the https://thegraph.com becomes status quo.

> working with numbers is a pain, it just silently rounds the data we send or get from the database

This sounds like very specific problem of specific database library. E.g. http://sequelize.org/ doesn't have this problem, as all decimals are represented by strings.
https://github.com/MikeMcl/big.js/ is pretty convenient if you actually need to do math on big decimals.

> There are far fewer backend devs in JS than the total number

data still not in favor of Rust
https://github.com/expressjs/express (48k stars)
https://github.com/actix/actix-web (7.7k stars)

> and it is much harder to review the code in JS than in Rust

It is very subjective what is easier to review just by looking at code diff. However when you are reviewing stuff on Rust – you are likely not running the code involved (or spending far more time to do it), as it takes forever to build/deploy specific PR. 
This is generally one of main problems spawning all other – it takes long time to build and deploy, so you won't be doing as many iterations as you can afford with virtually zero compilation time. 

>  Also, do we have much external contribution to our AppLayer projects? (on the Explorer, it is none)

We won't be getting meaningful external contribution before people can use our stuff to make money.

I think more immediate problem is that whoever is contributing to explorer frontend (even internally) now needs to use different tech stack to tinker with explorer backend. Making full-stack changes much harder. Once you need multiple people to implement single feature – everything generally takes order of magnitude longer.

**Comment by vgrichina** [comment]
I also kinda feel that for external users we might need a bit different kind of service – as app developer you'd likely want to only store/query data for a limited set of keys in a limited set of accounts. This should be much easier to scale in terms of storage (i.e. plausibly fits into single Postgres DB for a given app).

**Comment by vgrichina** [comment]
> Well, if that is the case, we should better implement it in Explorer backend since we almost have it.

How long will it take? Will it require WAMP for querying or regular HTTP requests can be supported?

**Comment by frol** [comment]
> if smth like the https://thegraph.com becomes status quo.

Using TheGraph to implement the indexer is the first thing I want to try doing.

> This sounds like very specific problem of specific database library. E.g. http://sequelize.org/ doesn't have this problem

We specifically use sequelize here...

> data still not in favor of Rust

https://github.com/expressjs/express (48k stars) 235 contributors
https://github.com/actix/actix-web (7.7k stars) 201 contributors

So in terms of the number contributors, they are on par even though actix-web has had a lot of drama about being hard to contribute to (not anymore, and not a general status of things in Rust ecosystem), and express is muuuch older project.

> needs to use different tech stack to tinker with explorer backend.

The idea is that this Indexer will become an external component serving not only Explorer, but also Wallet (I consider the current use of Explorer backend from Wallet to be a hack; @icerove did we create an issue to fix Actions in Wallet?), and the ownership will be transferred to the nearcore middleware team.

> Making full-stack changes much harder.

In general, I agree with this statement. Yet, what makes things really slow is not the language, but the compatibility. Having Explorer backend tightly focused on the frontend needs helps to iterate quickly, but given that more and more people want to use the service, we cannot keep it in Explorer codebase. And I believe, middleware team of nearcore is the right team to own the project (if we choose between chain, middleware and app layer)

> I also kinda feel that for external users we might need a bit different kind of service 

Exactly my thinking! Thanks for pointing this out! This is why I initially proposed to have a framework allowing people to implement any custom logic on top of the stream of events.

> How long will it take?

This can be done fairly quickly. My optimistic estimate is 2-3 days. The reason I have not done it is the priorities for the other tasks, and the fact that it was not required by Explorer yet.

> Will it require WAMP for querying or regular HTTP requests can be supported?

It will be WAMP. The implementation will only touch the synchronization part, so the API will be the same, just fetch the data from the relevant table with SQL query.

**Comment by vgrichina** [comment]
> We specifically use sequelize here...

Weird. Do you have more details on when numbers got rounded improperly? I didn't encounter it before with sequelize, but maybe I just didn't hit specific edge cases.

> So in terms of the number contributors, they are on par

Note that express is:
1) old shit in Node.js world, people moved on to other stuff
2) not as barebones as e.g. Koa, but even multipart handling not included in core (so a lot of contributions are going into separate express middleware projects)

In any case Rust vs JS is more a holywar of completely different approaches to development. I think it's pretty non-controversial that Rust is better for lower-level stuff that needs to be stable and better CPU performance and JS is better for higher-level stuff that needs to evolve fast and not heavy on CPU. I feel like stuff that's not nearcore is still in the "needs to evolve fast" category, but I also agree the for "indexer" it is debatable where it falls.   

> and the ownership will be transferred to the nearcore middleware team.

Not sure this is a good idea. So far nearcore has been a bit suboptimal with web APIs.

> The reason I have not done it is the priorities for the other tasks, and the fact that it was not required by Explorer yet.

It's not required by explorer, but we can unblock quite a few third-party integrations by this. It's also not strictly required, but useful for account recovery in our wallet (e.g. if you have a key on Ledger but don't remember your username).

So let's do it.

> It will be WAMP. The implementation will only touch the synchronization part, so the API will be the same, just fetch the data from the relevant table with SQL query.

We need to double check if it works for potential integrations. HTTP is easy to do for pretty much everything. WAMP has good coverage in terms of tech stacks, but not as good as HTTP.

**Comment by frol** [comment]
> So let's do it.

@icerove already started working on it #253. Please, let us know if you have any input on the plan we laid out in https://github.com/nearprotocol/near-explorer/issues/162#issuecomment-608709742

> We need to double check if it works for potential integrations.

Well, given currently we already have WAMP and the indexed data gets "automatically" exposed via WAMP, the first iteration will be WAMP-only, and later we may get back to it.

**Comment by frol** [comment]
TheGraph is overkill. It should be straightforward to implement Network Indexer based on the existing near-network implementation used for near nodes state sync.

**Comment by bowenwang1996** [comment]
@frol let's not do that in the short term. Do you know how many hours I have spent on debugging that syncing code? It is very easy to mess up and expose new vulnerabilities that are critical.

**Comment by frol** [comment]
@bowenwang1996 Explorer only needs it in a read-only mode. How can it expose vulnerabilities? Also, it is dogfooding, it may help to reveal sync problems earlier.

**Comment by nearmax** [comment]
@vgrichina 

> Dunno why you folks like using Rust for backend 

Because it is a safe language that removes possibilities of various mistakes? AFAIR we never had dangling pointers, data race, or use after free in nearcore. For such complex project it is a huge success. We also had only one or two problems with memory leaks, mostly around us misusing third-part libraries. If you wonder why we are not using languages with built-in memory management see: https://blog.discord.com/why-discord-is-switching-from-go-to-rust-a190bbca2b1f

> so much given nearcore RPC experience

What are the issues with nearcore RPC experience?

> Rust will discourage open source contributions, as there are far more JS developers than Rust developers.

Using JS will make lots of low-level optimizations impossible. In general, we should be always preferring the language that dominates in our organization, because then more engineers will be able to review/read/contribute to the project.

> It's also looks like generally resulting far longer dev cycles (based on nearcore experience).

That's because our nearcore development is throttled by the research that we were constantly doing in parallel to writing code. If we want to compare nearcore dev cycles then we need to compare it to other R&D heavy projects.

> @frol this is highly desired for MainNet but not strictly a blocker. 

As discussed during our engineering meetings, the definition of the Mainnet blocker is fuzzy, especially when it comes to Applayer and DevX. If someone is highly desirable and requested then while it is not strictly blocking our launch we sometimes choose to work on it in parallel with the tasks that are strictly blocking the launch. This decision however is a judgement call which requires long discussion, which I assume was done during the Applayer syncs and the Explorer syncs.

> Most of "Indexer" stuff is likely going to be completely deprecated if smth like the https://thegraph.com becomes status quo.

AFAIU @frol did an extensive research with the goal to replace explorer backend with theGraph. Unfortunately, he discovered that in the short-term implementing our own indexer would be fater. Note, that third-party integration requires writing glue code, which will be especially complex around the parts that are specific to our blockchain design, like sharding and chunks.

> Not sure this is a good idea. So far nearcore has been a bit suboptimal with web APIs.

For the same reason Applayer was constantly broken by nearcore -- it is a downstream consumer of changes. RPC client was constantly broken and remade. Plus the reason it is like that is because we were trying to follow the existing blockchain RPC API standards, like Cosmos, which are different then what is commonly done in web APIs.

@frol 

> and the ownership will be transferred to the nearcore middleware team.

I double that. The scope of the Middleware team is -- computation of the truth, access to the truth, and storage of the truth. It does not include presentation of the truth. Indexer is the access to the truth (people developing it are required to understand how to correctly aggregate and flatten the data, which is better done by someone working on the explorer). While explorer front-end is the presentation of the truth.

> It should be straightforward to implement Network Indexer based on the existing near-network implementation used for near nodes state sync.

I agree with @bowenwang1996  that we should reconsider using network crate as is, but for a different reason. I don't think it presents safety issues. I think we won't be able to use network crate without using the fork-choice rule stuff. Basically explorer would need to implement a complete standalone light client for that, which stretches the scope of this issues a bit too much.

**Comment by frol** [comment]
> I think we won't be able to use network crate without using the fork-choice rule stuff.

Is it part of near-chain? Is it too complex?

> need to implement a complete standalone light client for that

I recall we had some conversations about the light client, but I did not follow its state. Do we have it in some form?

**Comment by nearmax** [comment]
> Is it part of near-chain? Is it too complex?

It is unclear to me how hard would it be to carve out. I like the idea of having light client and fork choice rules implemented as two separate crates, because then we can reuse it in other places in the future (For example we could add an option to near-sdk-js to run as a non-validating node, i.e. instead of trusting the node it connects to it would run against the entire network, keep track of the canonical chain itself, and validate it using light client rules.) However, I am concerned that it might take quite a long time to assemble it all, because just reading the network code might be a long and complex task that would take us way beyond the scope of the network indexer. The reason why we would need both light client and the fork choice rule is because AFAIU network crate does not understand what is canonical chain so it cannot produce input for the light client on its own.

@mfornet @SkidanovAlex how hard is it to implement non-validating node that tracks all shards, using network crate, fork choice rule and the light client rules of validation?

> I recall we had some conversations about the light client, but I did not follow its state. Do we have it in some form?
https://github.com/nearprotocol/NEPs/pull/60

**Comment by bowenwang1996** [comment]
> how hard is it to implement non-validating node that tracks all shards, using network crate, fork choice rule and the light client rules of validation?

It is probably harder to implement light client logic than to modify existing code and use some mostly no-op runtime. Light client doesn't track any shard and only knows about headers. That is obviously not something that we need here. My guess is that it should not be super difficult to switch to no-op runtime, but there can be unforeseen challenges.

**Comment by nearmax** [comment]
@bowenwang1996 light client does not understand what canonical chain is either. AFAIU something needs to be feeding the light client the headers that correspond to the current canonical chain, i.e. the fork choice rule. How hard is it to extract the fork choice rule?

**Comment by SkidanovAlex** [comment]
> how hard is it to implement non-validating node that tracks all shards, using network crate, fork choice rule and the light client rules of validation?

We can add a concept of a light client peer, and have full nodes send them light client blocks periodically (light client blocks are a chain, not a tree, and don't need any complex fork choice rule), but it is not implemented today.

**Comment by nearmax** [comment]
Discussed with @SkidanovAlex . We need glue code to take blocks from the network crate and produce light client blocks, this is not a small amount of work, so for now we should stick with RPC.

**Comment by frol** [comment]
@bowenwang1996 @SkidanovAlex @nearmax what if we take nearcore and, basically, replace jsonrpc with a watcher module that will monitor all the data and save it into the structure we need for indexing? Do you still think it is unrealistic? I really don’t want to work on the RPC level anymore, it is way too much work (sometimes the workflow is as deep as: expose the data via chain/client, expose it via RPC, make sure that the RPC API is sane and generic, deploy and document it, and only after that I could get back to Explorer backend implementation)

**Comment by bowenwang1996** [comment]
> replace jsonrpc with a watcher module that will monitor all the data and save it into the structure we need for indexing

How does it work exactly? It seems that you want some sort of push model rather than polling information.

**Comment by frol** [comment]
> It seems that you want some sort of push model rather than polling information.

Exactly

**Comment by frol** [comment]
> How does it work exactly?

There are different levels where we can intercept the data:

* Store (RocksDB) - probably, too low-level
* process_block (apply_chunk) in near-chain - I have little familiarity with the codebase
* [the simplest option] use near-client to fetch all the information we otherwise fetch for JSON RPC; fetch the data in a "busy loop" - this still cuts the corner of needing to extend JSON RPC for various reasons

In the end, instead of running archival nodes + Explorer backend (as we do it now), we will be able to run a single modified nearcore instance to follow the network and index it along its way.

**Comment by bowenwang1996** [comment]
> use near-client to fetch all the information we otherwise fetch for JSON RPC; fetch the data in a "busy loop" - this still cuts the corner of needing to extend JSON RPC for various reasons

It sounds like still a polling model, but yeah it will be more direct. Although it might take some effort to implement this.

**Comment by frol** [comment]
@bowenwang1996 well, JSON RPC is not a free lunch, we constantly hit its limitations only required for projects like Explorer, and after we build JSON RPC, we still build Explorer RPC to expose the indexed data, and it is proved to be a really slow process, and we still have bugs like these: #223, #252, and long-standing feature-requests https://github.com/nearprotocol/nearcore/issues/1880 on nearcore.

**Comment by nearmax** [comment]
Implementing explorer over RPC creates large maintenance overhead and limits what kind of information it can access and how. If we just have an "indexer node" that has an additional actor that monitors internal events and dumps flattened data to a separate database then we can:
* iterate faster;
* benefit from the direct access to the internals;
* make it run faster, since we don't need to serialize/deserialize through RPC;
* do not write glue code around RPC.

**Comment by frol** [comment]
To summarize the call we had last week, we are going to build Network Indexer using nearcore codebase. The plan is the following:

* Rely on the nearcore network synchronization capabilities of an archival node mode (read about the caveats below)
* Build a new component (crate) to nearcore (`streamer`), which will use view_client capabilities in a busy loop to fetch the new block (+ chunks, transactions, receipts, outcomes).

  *NOTE: Take inspiration from `nearcore/chain/jsonrpc` implementation, where instead of reacting to external requests we should spawn a busy loop, which will communicate with view_client fetching the relevant information.*
* Design the framework to make it reasonably easy to plug into the `streamer` (it is not a separate process, it all should happen inside the nearcore process, just on different layers of abstraction) to receive the new blocks
* Using the framework, implement Access Keys Indexer storing the mapping of the public access key to the account ID (let's start with a plain Rust HashMap; this is fairly simple use case allowing us to test the design).

  *NOTE: We should track the receipts for `AddKey` action and only apply those once we know that the receipt execution is successful.*
* Using the framework, implement Explorer Indexer storing all the blocks, chunks, transactions, receipts, outcomes into PostgreSQL (this is what, for example, Render.com and AWS provide as a hosted solution)

Caveats:

1. nearcore archival node does not have back filling implementation, so it does not fill the gaps when it was offline. @bowenwang1996 considers this to be a missing feature for the archival node, so it will be implemented one day. Network Indexer is not blocked on that since (2)
2. nearcore has a mode that disables state sync from some epoch boundary and instead can be configured to replay the history from the genesis. (/cc @bowenwang1996 please, point us to the configuration option we need to tweak) This will take quite some time to catch up with the latest state, but we are good to go with this solution for now.

@khorolets Let's have the first steps:

1. Build nearcore and learn how jsonrpc implementation gets information about status, blocks, chunks, transactions, etc. I think, RPC API documentation may help you: https://docs.near.org/docs/interaction/rpc
2. Create a new crate `nearcore/chain/streamer` (our busy loop will live there) and plug it into `nearcore/neard` - get the busy loop spawned. Success is: the `status` is printed from the busy loop once the status gets changed (fetch if every 0.5 second and compare with the previously fetched value)

**Comment by bowenwang1996** [comment]
@frol Actually I double checked my approach and it might be too slow to be acceptable without modifying nearcore code (when there are millions of blocks in the network). So we should probably wait for the proper implementation of archival node, though I don't think it is blocking for now.

On the other hand, I want to discuss whether keeping network indexer tightly coupled with nearcore code is the way to go. Is this the long term plan?

**Comment by frol** [comment]
I would say that the long-term plan is to be dependent on the near-chain / near-network (i.e. re-use the communication protocol and the chain rules). The ultimate goal for the indexer is to get the stream of blocks with chunks, transactions, receipts, and execution outcomes, we don't even need to save those into RocksDB or such (imagine I only want to build an indexer of account access keys, so I only care about the state change related to the account keys [AddKey, DeleteKey, DeleteAccount actions may affect it, AFAIK]).

Thus, it is just a shortcut that we decided to let nearcore work as usual and pull the necessary data from it via near-client.

**Comment by frol** [comment]
Some extra vision (no changes, just an addition to the big picture):

We are going to build a Network Indexer framework based on nearcore internals and thus we will be able to build all sorts of various types of reactors. Imagine the following:

1. create a new Rust binary project
2. add `near-indexer` dependency
3. write a reactor:

    ```rust
    let mut stream = near_indexer::start();
    while let Some(new_block) = stream.next().await {
        // condition on the block content, transform, filter, send to whatever storage, push to an event handling service
    }
    ```
4. run it on-premise and have your own control over it (from the NEAR network point of view, it is going to be just another peer with all the same features)

I imagine we are going to build a few common indexers:
* [proxy indexer] - just pass the blocks into some external service (e.g. Kafka, Spark, RabbitMQ, ZMQ)
* [archival SQL indexer - Explorer-like] all the blocks, chunks, transactions, receipts, execution outcomes get stored into SQL DB
* [access keys indexer] - only maintain the access key <=> account ID mapping (requested by wallets for passphrase recovery)

Proxy indexer is useful for those who don't want to hack in Rust, and thus they can handle the events in a separate service.

**Comment by frol** [comment]
Quick update: NEAR Indexer framework is ready to land to nearcore (https://github.com/nearprotocol/nearcore/pull/2651). Those, who want to implement their own indexer can start poking it around following the README in the PR, and ask questions, so we improve the documentation / examples / code.

**Comment by frol** [comment]
NEAR Indexer has landed: https://github.com/nearprotocol/nearcore/tree/master/chain/indexer

The next step is the implementation of NEAR Wallet Indexer (should be small while super important) solving the specific problem of Wallet of keeping track of all the access keys including the ones added from contracts.

NEAR Explorer Indexer is the next step after NEAR Wallet Indexer.

**Comment by frol** [comment]
Resolved with [Indexer for Explorer](https://github.com/near/near-indexer-for-explorer)
