### ISSUE TITLE
Explorer does not show all transactions

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#322]
Take this account https://explorer.betanet.near.org/accounts/villiamsivertsen for example. On the account page it shows that there are 90 transactions but it only displays 20 transactions and seems to get stuck on loading the rest with error "Failed to load resource: the server responded with a status of 404 ()".

**Comment by frol** [comment]
@icerove I believe the problem is that one of the archival nodes missed the transaction that we try to fetch. We fetch that information to display the status (success or failure). We should eventually store the status in Explorer database.

Meanwhile, let's make the transaction status fetching so it does not block transaction details rendering.

**Comment by icerove** [comment]
@frol do you mean fetching the status in another function call and do not include it in the getTransactions function and not let the status fetching failure affect the transactions fetching?

**Comment by frol** [comment]
That is exactly what I meant 👍
