### ISSUE TITLE
Node page descriptions and titles

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#366]
### Overview
Suggesting the following changes to the `/nodes` page titles and tabs, along with descriptions for the types of nodes. cc @icerove @frol @bowenwang1996 @jimmy3dita for comments.

![Screen Shot 2020-07-27 at 5 11 24 PM](https://user-images.githubusercontent.com/5624527/88604835-21f48480-d02d-11ea-8b7e-cbe2af2288c4.png)

**Title/tab label**: Validators
**Description**: The current set of validating nodes for this epoch.

**Title/tab label**: Nodes Online
**Description**: Nodes that are online, but not serving as validators

**Title/tab label**: Proposing
**Description**: Nodes that have staked to be included in the next epoch's validator set.

**Comment by frol** [comment]
I want to make sure we don't confuse people with what "validator" term means. In my opinion, we have enough confusion already.

The Nodes pages are about nodes, not about accounts or humans, and I propose we call the nodes that do validation as "validation nodes", while the humans, who operate those nodes, are validators, and the accounts the validators use to stake [propose] are validator accounts. Does it make sense to anyone? /cc @amgando @potatodepaulo @vgrichina @jimmy3dita @ilblackdragon @bowenwang1996

**Comment by bowenwang1996** [comment]
@frol I think that is too confusing. People don't like to read things and if you juxtapose "validation nodes", "validators", and "validator accounts", it will create a lot of confusion.

**Comment by frol** [comment]
Calling a person and a node "a validator" does not help either, in my opinion. "validator_key.json" is already bad enough to confuse the validators [people]; I mean that a validator has their account and a key for that account (that can be called a validator key since it is a key of a validator), and then we create a `validator_key.json`, which is a separate thing, it is used to perform validation of the blocks/chunks on behalf of the specified validator account_id. :man_shrugging:

**Comment by bowenwang1996** [comment]
Yeah I agree. I think the meaning of validator has definitely been conflated in the blockchain space. I am not sure how to best disentangle the pieces here.

**Comment by frol** [comment]
It is not relevant after #613
