### ISSUE TITLE
Design display for long account IDs (e.g. implicit accounts)

### ISSUE THREAD

**Issue by frol** [near/near-explorer#427]
## Story

In some places, we don't have enough space to display such long account ids:

![image](https://user-images.githubusercontent.com/304265/94252063-cf82f780-fef9-11ea-8180-eb6ed73ba729.png)

![image](https://user-images.githubusercontent.com/304265/94252097-d90c5f80-fef9-11ea-85eb-51d5da87917f.png)

**Comment by icerove** [comment]
give it proper truncated on display and tooltip on hover for full?

**Comment by corwinharrell** [comment]
Common practice in Ethereum for addresses is to display a portion of both the beginning and end of an address, with an ellipses in between. I suggest we follow this pattern as it's fairly familiar.

So as an example, an account ID would be truncated like: `094hfj...0284hr`

We should remove the `@` symbol as well, since we have decided to remove it from account names in the wallet.
