### ISSUE TITLE
Smooth out last day stats

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#570]
Open https://explorer.near.org/stats page
Observe that current day only has "36" tx in chart below, which seems weird.
Either let's not show the last day or show stats the last 24h.

<img width="1074" alt="Screen Shot 2021-03-01 at 5 12 26 PM" src="https://user-images.githubusercontent.com/175486/109581575-5d6a9c00-7ab1-11eb-9091-0ec11d1d572e.png">

**Comment by frol** [comment]
@icerove let's cut the last day to avoid this situation.

**Comment by icerove** [comment]
I don't think it is reasonable to cut last day since it is changing while we query from indexer. It is kind of real time and if we cut off last day and just get yesterday history, is that the case we want? @ilblackdragon  @frol

**Comment by frol** [comment]
@icerove If we don't cut the last day (which is incomplete) we always give an impression that the trend is down. It is misleading and not really useful, which is why on the main Dashboard we have the last day cut off from the transactions history chart, and instead, we have the last 24h transactions count as a separate cell.
