### ISSUE TITLE
Number of transactions does not load for some accounts

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#699]
For example, https://explorer.near.org/accounts/canvas-war.feiyu.near does not show the number of transactions
<img width="1122" alt="Screen Shot 2021-08-06 at 10 05 54 AM" src="https://user-images.githubusercontent.com/13601726/128546903-87a772a1-b707-4ac4-8367-aff2ad41d0d5.png">

**Comment by frol** [comment]
This particular behavior is a hotfix that I deployed to make it possible to open the account page in the first place since counting the number of transactions just runs out of resources and does not complete in any reasonable time.

The path forward is:

* decouple the transactions counting from the initial page load and introduces the loader bahaviour. This won't help the traffic-heavy accounts to display the number of transactions, but will work fine for the low-traffic accounts (@shelegdmitriy is working on this)
* optimize the way we get the number of transactions by pre-aggregating the numbers daily on the Indexer for Explorer side (@telezhnaya is working on this)
