### ISSUE TITLE
Wrong number of validating nodes on the `/nodes/validators` page

### ISSUE THREAD

**Issue by nikurt** [near/near-explorer#793]
Both `near-cli` and `INFO` logs of the nodes agree that the number of validating nodes is 65 (for testnet, during the current epoch).
https://explorer.testnet.near.org/nodes/validators says that the number of validating nodes is 91.

Would be nice to see a consistent number of validating nodes on the explorer page.

**Comment by frol** [comment]
@shelegdmitriy We need to revisit what we count as the number of validators. That should be the number of validation nodes in the current epoch

**Comment by shelegdmitriy** [comment]
We receive the validators list from this query https://github.com/near/near-explorer/blob/master/backend/src/near.js#L30. After that we add `active`, `leaving` and `joining` statuses (https://github.com/near/near-explorer/blob/master/backend/src/near.js#L129-L143) and then we just calculate them (https://github.com/near/near-explorer/blob/master/backend/src/index.js#L279). So, the number of validating nodes depends on these (`active`, `leaving` and `joining`) types of validators which is not true. because of:

1. `active` means validator in this epoch;
2. `leaving` means validator validate in this epoch but not in the next one;
3. `joining` means validator isn't validate in this epoch but will be in the next one;

I think we should filter the list of all validators by `active` and `leaving` statuses to display the number of validating nodes properly.

@frol WDYT?

FYI: if I made as I sayed then on **mainnet** the number of validating nodes is 61 (nothing changed) and on **testnet** is 72

**Comment by frol** [comment]
@shelegdmitriy Yes, that is right, we should count active & leaving. We messed up the terminology of `currentValidators` here: https://github.com/near/near-explorer/blob/master/backend/src/near.js#L141 (joining should not be part of `currentValidators`, but they are... :confused:)

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy Yes, that is right, we should count active & leaving. We messed up the terminology of `currentValidators` here: https://github.com/near/near-explorer/blob/master/backend/src/near.js#L141 (joining should not be part of `currentValidators`, but they are... 😕)

Yes, `currentValidators` name is confusing, I'll think and rename it as well
